# Generated by Django 4.2.11 on 2024-04-03 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_salaryreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalaryReport',
        ),
    ]
